{{ config(materialized='table') }}

SELECT 
    CMS_CERTIFICATION_NUMBER_CCN AS CMS_CCN,
    PROVIDER_NAME AS FACILITY_NAME,
    PROVIDER_ADDRESS AS FACILITY_ADDRESS,
    CITY_TOWN AS CITY,
    STATE AS STATE,
    ZIP_CODE AS ZIP_CODE,
    TELEPHONE_NUMBER AS PHONE_NUMBER,
    LOCATION AS LOCATION,
    NUMBER_OF_CERTIFIED_BEDS AS CERTIFIED_BEDS,
     AVERAGE_RESIDENTS_PER_DAY AS AVG_RESIDENTS_PER_DAY,
    OWNERSHIP_TYPE AS OWNERSHIP_TYPE,
    PROVIDER_TYPE AS FACILITY_TYPE,
    CONTINUING_CARE_RETIREMENT_COMMUNITY AS IS_CONTINUING_CARE,
    PROVIDER_RESIDES_IN_HOSPITAL AS IN_HOSPITAL,
    WITH_A_RESIDENT_AND_FAMILY_COUNCIL AS RESIDENT_COUNCIL,
    AUTOMATIC_SPRINKLER_SYSTEMS_IN_ALL_REQUIRED_AREAS AS SPRINKLER_SYSTEM,
    SPECIAL_FOCUS_STATUS AS SPECIAL_FOCUS,
    HEALTH_INSPECTION_RATING AS HEALTH_INSPECTION_RATING,
    OVERALL_RATING AS OVERALL_RATING
    --REPORT_DATE AS REPORT_DATE,
    --REPORT_MONTH
FROM 
    {{ ref('nh_provider_info') }}

