{{ config(materialized='table') }}

SELECT 
    CMS_CERTIFICATION_NUMBER_CCN,
    ZIP_CODE,
    LOCATION,
    CITY_TOWN,
    STATE,
    PROVIDER_ADDRESS,
    --REPORT_MONTH,
    --REPORT_DATE,
    PENALTY_TYPE,
    SUM(FINE_AMOUNT) AS TOTAL_FINE_AMOUNT,
    SUM(PAYMENT_DENIAL_DAYS) AS TOTAL_PAYMENT_DENIAL_DAYS,
    MIN(PAYMENT_DENIAL_START_DATE) AS FIRST_PAYMENT_DENIAL_DATE,
    MIN(PENALTY_DATE) AS FIRST_PENALTY_DATE,
    MAX(PROCESSING_DATE) AS LATEST_PROCESSING_DATE
FROM {{ ref('nh_penalties') }}
GROUP BY 
    CMS_CERTIFICATION_NUMBER_CCN,
    ZIP_CODE,
    LOCATION,
    CITY_TOWN,
    STATE,
    PROVIDER_ADDRESS,
    --REPORT_MONTH,
    --REPORT_DATE,
    PENALTY_TYPE
