{{ config(materialized='table') }}
SELECT
    COALESCE(mds.CMS_CERTIFICATION_NUMBER_CCN, claims.CMS_CERTIFICATION_NUMBER_CCN) AS CMS_CERTIFICATION_NUMBER_CCN,
    COALESCE(mds.PROVIDER_NAME, claims.PROVIDER_NAME) AS PROVIDER_NAME,
    COALESCE(mds.PROVIDER_ADDRESS, claims.PROVIDER_ADDRESS) AS PROVIDER_ADDRESS,
    COALESCE(mds.CITY_TOWN, claims.CITY_TOWN) AS CITY_TOWN,
    COALESCE(mds.STATE, claims.STATE) AS STATE,
    COALESCE(mds.ZIP_CODE, claims.ZIP_CODE) AS ZIP_CODE,
    COALESCE(mds.MEASURE_CODE, claims.MEASURE_CODE) AS MEASURE_CODE,
    COALESCE(mds.MEASURE_DESCRIPTION, claims.MEASURE_DESCRIPTION) AS MEASURE_DESCRIPTION,
   mds.MEASURE_PERIOD AS MEASURE_PERIOD,
    COALESCE(mds.RESIDENT_TYPE, claims.RESIDENT_TYPE) AS RESIDENT_TYPE,
    -- MDS-specific columns
    mds.FOUR_QUARTER_AVERAGE_SCORE AS MDS_FOUR_QUARTER_AVERAGE,
    mds.Q1_MEASURE_SCORE AS MDS_Q1_SCORE,
    mds.Q2_MEASURE_SCORE AS MDS_Q2_SCORE,
    mds.Q3_MEASURE_SCORE AS MDS_Q3_SCORE,
    mds.Q4_MEASURE_SCORE AS MDS_Q4_SCORE,
    mds.FOOTNOTE_FOR_FOUR_QUARTER_AVERAGE_SCORE AS MDS_AVG_FOOTNOTE,
    mds.FOOTNOTE_FOR_Q1_MEASURE_SCORE AS MDS_Q1_FOOTNOTE,
    mds.FOOTNOTE_FOR_Q2_MEASURE_SCORE AS MDS_Q2_FOOTNOTE,
    mds.FOOTNOTE_FOR_Q3_MEASURE_SCORE AS MDS_Q3_FOOTNOTE,
    mds.FOOTNOTE_FOR_Q4_MEASURE_SCORE AS MDS_Q4_FOOTNOTE,
    
    -- Claims-specific columns
    claims.ADJUSTED_SCORE AS CLAIMS_ADJUSTED_SCORE,
    claims.OBSERVED_SCORE AS CLAIMS_OBSERVED_SCORE,
    claims.EXPECTED_SCORE AS CLAIMS_EXPECTED_SCORE,
    claims.FOOTNOTE_FOR_SCORE AS CLAIMS_FOOTNOTE,
    
    -- Common temporal columns
    --COALESCE(mds.REPORT_DATE, claims.REPORT_DATE) AS REPORT_DATE,
    --COALESCE(mds.REPORT_MONTH, claims.REPORT_MONTH) AS REPORT_MONTH,
    COALESCE(mds.PROCESSING_DATE, claims.PROCESSING_DATE) AS PROCESSING_DATE,
    COALESCE(mds.USED_IN_QUALITY_MEASURE_FIVE_STAR_RATING, claims.USED_IN_QUALITY_MEASURE_FIVE_STAR_RATING) AS USED_IN_FIVE_STAR_RATING
    
FROM  {{ ref('nh_quality_msr_mds') }}  mds
 left JOIN {{ ref('nh_quality_msr_claims') }} claims
    ON mds.CMS_CERTIFICATION_NUMBER_CCN = claims.CMS_CERTIFICATION_NUMBER_CCN
    AND mds.MEASURE_CODE = claims.MEASURE_CODE
    --AND mds.MEASURE_PERIOD = claims.MEASURE_PERIOD