{{ config(materialized='table') }}

WITH staffing AS (
     
   SELECT 
    CMS_CERTIFICATION_NUMBER_CCN AS CMS_CCN,
    REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS RN_HOURS_PER_DAY,
    REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS LPN_HOURS_PER_DAY,
    REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS CNA_HOURS_PER_DAY,
    REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND AS RN_HOURS_WEEKEND,
    TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND AS TOTAL_HOURS_WEEKEND,
    REGISTERED_NURSE_TURNOVER AS RN_TURNOVER,
    TOTAL_NURSING_STAFF_TURNOVER AS NURSING_STAFF_TURNOVER,
    STAFFING_RATING AS STAFFING_RATING,
    ADMINISTRATOR_TURNOVER_FOOTNOTE AS ADMINISTRATOR_TURNOVER_INFO
    --REPORT_DATE,
    --REPORT_MONTH
    FROM {{ ref('nh_provider_info') }}
    
)

SELECT * FROM staffing
