name: 'healthcare_project'
version: '1.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
dispatch:
  - macro_namespace: dbt
    search_order: ['healthcare_project', 'dbt']

vars:
  target_db: 'healthcaredb'
models:
  healthcare_project:
    +materialized: table  # Default materialization for all models

    bronze:
      +enabled: true

    silver:
      +schema: silver
      +materialized: table
      staging:  # Optional sub-folder under silver/
        +materialized: view

    gold:
      +schema: gold
      +materialized: table
