{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}



SELECT 
    DEFICIENCY_CATEGORY::STRING AS DEFICIENCY_CATEGORY,
    DEFICIENCY_PREFIX::STRING AS DEFICIENCY_PREFIX,
    DEFICIENCY_DESCRIPTION::STRING AS DEFICIENCY_DESCRIPTION,
    DEFICIENCY_PREFIX_AND_NUMBER::STRING AS DEFICIENCY_PREFIX_AND_NUMBER,
    DEFICIENCY_TAG_NUMBER::INTEGER AS DEFICIENCY_TAG_NUMBER
   -- REPORT_DATE::DATE AS REPORT_DATE,
   -- REPORT_MONTH::STRING AS REPORT_MONTH
FROM {{ source('BRONZE', 'NH_CITATION_DESCRIPTIONS') }}

