{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}

SELECT 
    CMS_CERTIFICATION_NUMBER_CCN,
    DATE_VACCINATION_DATA_LAST_UPDATED,
    STATE,
    REPORT_DATE,
    REPORT_MONTH,
    TRY_TO_NUMBER(PERCENT_OF_STAFF_WHO_ARE_UP_TO_DATE_ON_THEIR_VACCINES) AS PERCENT_OF_STAFF_WHO_ARE_UP_TO_DATE_ON_THEIR_VACCINES,
    TRY_TO_NUMBER(PERCENT_OF_RESIDENTS_WHO_ARE_UP_TO_DATE_ON_THEIR_VACCINES) AS PERCENT_OF_RESIDENTS_WHO_ARE_UP_TO_DATE_ON_THEIR_VACCINES
FROM {{ source('BRONZE', 'NH_COVID_VAX_PROVIDER') }}
