{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}


SELECT 
    MEASURE_CODE,
    TRY_TO_DATE(NULLIF(DATA_COLLECTION_PERIOD_THROUGH_DATE::STRING, 'nan')) AS END_DATE,
    TRY_TO_DATE(NULLIF(DATA_COLLECTION_PERIOD_FROM_DATE::STRING, 'nan')) AS START_DATE,
    TRY_TO_DATE(NULLIF(PROCESSING_DATE::STRING, 'nan')) AS PROCESSING_DATE,
    MEASURE_DESCRIPTION,
    MEASURE_DATE_RANGE
    --TRY_TO_DATE(NULLIF(REPORT_DATE::STRING, 'nan')) AS REPORT_DATE,
    --REPORT_MONTH
FROM {{ source('BRONZE', 'NH_DATA_COLLECTION_INTERVALS') }}
