{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}

SELECT 
    TRY_TO_DATE(NULLIF(SURVEY_DATE, 'nan')) AS SURVEY_DATE ,
ZIP_CODE,
DEFICIENCY_CATEGORY,
CITATION_UNDER_IIDR
CITY_TOWN,
INSPECTION_CYCLE,
INFECTION_CONTROL_INSPECTION_DEFICIENCY,
PROVIDER_ADDRESS,
TRY_TO_DATE(NULLIF(CORRECTION_DATE, 'nan')) AS CORRECTION_DATE, 
LOCATION,
DEFICIENCY_PREFIX,
STANDARD_DEFICIENCY,
--REPORT_MONTH,
PROVIDER_NAME,
COMPLAINT_DEFICIENCY,
STATE,
SCOPE_SEVERITY_CODE,
DEFICIENCY_DESCRIPTION,
TAG_VERSION,
DEFICIENCY_TAG_NUMBER,
PROCESSING_DATE,
DEFICIENCY_CORRECTED,
CMS_CERTIFICATION_NUMBER_CCN,
CITATION_UNDER_IDR,
--REPORT_DATE::DATE as REPORT_DATE,
SURVEY_TYPE 
FROM {{ source('BRONZE', 'NH_FIRE_SAFETY_CITATIONS') }}