{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}
SELECT 
COMPLAINT_DEFICIENCY,
CMS_CERTIFICATION_NUMBER_CCN,
INSPECTION_CYCLE,
PROVIDER_ADDRESS,
STANDARD_DEFICIENCY,
SURVEY_TYPE,
CITATION_UNDER_IIDR,
TRY_TO_DATE(NULLIF(REPORT_DATE, 'nan')) AS REPORT_DATE ,
ZIP_CODE,
CITATION_UNDER_IDR,
SCOPE_SEVERITY_CODE,
REPORT_MONTH,
CITY_TOWN,
PROVIDER_NAME,
TRY_TO_DATE(NULLIF(PROCESSING_DATE, 'nan')) AS PROCESSING_DATE ,
DEFICIENCY_CORRECTED,
DEFICIENCY_CATEGORY,
DEFICIENCY_DESCRIPTION,
DEFICIENCY_TAG_NUMBER,
TRY_TO_DATE(NULLIF(CORRECTION_DATE, 'nan')) AS CORRECTION_DATE,
INFECTION_CONTROL_INSPECTION_DEFICIENCY,
DEFICIENCY_PREFIX,
TRY_TO_DATE(NULLIF(SURVEY_DATE, 'nan')) AS SURVEY_DATE,
STATE,
LOCATION
FROM {{ source('BRONZE', 'NH_HEALTH_CITATIONS') }}