{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}

SELECT 
    TRY_TO_DATE(NULLIF(PROCESSING_DATE::STRING, 'nan')) AS PROCESSING_DATE, 
    PROVIDER_NAME,
    PROVIDER_ADDRESS,
    OWNER_NAME,
    LOCATION,
    ROLE_PLAYED_BY_OWNER_OR_MANAGER_IN_FACILITY AS MANAGER_IN_FACILITY,
    --REPORT_MONTH,
    TRY_TO_DATE(NULLIF(ASSOCIATION_DATE::STRING, 'nan')) AS ASSOCIATION_DATE, 
    --TRY_TO_DATE(NULLIF(REPORT_DATE::STRING, 'nan')) AS REPORT_DATE, 
    TRY_TO_NUMBER(REPLACE(OWNERSHIP_PERCENTAGE, '%', '')) AS OWNERSHIP_PERCENTAGE,
    OWNER_TYPE,
    ZIP_CODE,
    STATE,
    CMS_CERTIFICATION_NUMBER_CCN,
    CITY_TOWN
FROM {{ source('BRONZE', 'NH_OWNERSHIP') }}
