{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}
SELECT 
FINE_AMOUNT::FLOAT as FINE_AMOUNT,
PENALTY_TYPE,
PAYMENT_DENIAL_LENGTH_IN_DAYS::int as PAYMENT_DENIAL_DAYS,
CMS_CERTIFICATION_NUMBER_CCN,
ZIP_CODE,
LOCATION,
TRY_TO_DATE(NULLIF(PAYMENT_DENIAL_START_DATE, 'nan')) AS PAYMENT_DENIAL_START_DATE ,
TRY_TO_DATE(NULLIF(PROCESSING_DATE, 'nan')) AS PROCESSING_DATE ,
CITY_TOWN,
STATE,
PROVIDER_ADDRESS,
TRY_TO_DATE(NULLIF(PENALTY_DATE, 'nan')) AS PENALTY_DATE 
--REPORT_MONTH,
--TRY_TO_DATE(NULLIF(REPORT_DATE, 'nan')) AS REPORT_DATE 

FROM {{ source('BRONZE', 'NH_PENALTIES') }}