{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}
SELECT 
PROCESSING_DATE,MEASURE_PERIOD,CMS_CERTIFICATION_NUMBER_CCN,FOUR_QUARTER_AVERAGE_SCORE
,Q2_MEASURE_SCORE,ZIP_CODE,FOOTNOTE_FOR_Q3_MEASURE_SCORE,
FOOTNOTE_FOR_Q2_MEASURE_SCORE,REPORT_DATE,
Q4_MEASURE_SCORE,
Q3_MEASURE_SCORE,
MEASURE_DESCRIPTION,PROVIDER_NAME,
RESIDENT_TYPE,MEASURE_CODE,Q1_MEASURE_SCORE,
REPORT_MONTH,FOOTNOTE_FOR_FOUR_QUARTER_AVERAGE_SCORE,
STATE,LOCATION,PROVIDER_ADDRESS,CITY_TOWN,FOOTNOTE_FOR_Q4_MEASURE_SCORE,FOOTNOTE_FOR_Q1_MEASURE_SCORE,USED_IN_QUALITY_MEASURE_FIVE_STAR_RATING
FROM {{ source('BRONZE', 'NH_QUALITY_MSR_MDS') }}
