{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}

SELECT 
COUNT_OF_NUTRITION_AND_DIETARY_DEFICIENCIES, 
FIRE_SAFETY_SURVEY_DATE, 
COUNT_OF_EMERGENCY_PLANS_AND_FIRE_DRILLS_DEFICIENCIES, 
PROVIDER_ADDRESS, 
COUNT_OF_ELECTRICAL_DEFICIENCIES, 
COUNT_OF_EGRESS_DEFICIENCIES, 
COUNT_OF_LABORATORIES_DEFICIENCIES, 
STATE, 
COUNT_OF_ADMINISTRATION_DEFICIENCIES, 
COUNT_OF_RESIDENT_RIGHTS_DEFICIENCIES, 
COUNT_OF_INFECTION_CONTROL_DEFICIENCIES, 
COUNT_OF_SERVICES_DEFICIENCIES, 
COUNT_OF_RESIDENT_ASSESSMENT_AND_CARE_PLANNING_DEFICIENCIES, 
COUNT_OF_NURSING_AND_PHYSICIAN_SERVICES_DEFICIENCIES, 
CITY_TOWN, 
COUNT_OF_CORRIDOR_WALLS_AND_DOORS_DEFICIENCIES, 
ZIP_CODE, 
COUNT_OF_PHARMACY_SERVICE_DEFICIENCIES, 
COUNT_OF_GAS_AND_VACUUM_AND_ELECTRICAL_SYSTEMS_DEFICIENCIES, 
COUNT_OF_FREEDOM_FROM_ABUSE_AND_NEGLECT_AND_EXPLOITATION_DEFICIENCIES, 
HEALTH_SURVEY_DATE, COUNT_OF_MEDICAL_GASES_AND_ANAESTHETIZING_AREAS_DEFICIENCIES, 
PROCESSING_DATE, REPORT_MONTH, TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES, 
COUNT_OF_SMOKE_DEFICIENCIES, PROVIDER_NAME, COUNT_OF_SMOKING_REGULATIONS_DEFICIENCIES, 
COUNT_OF_EMERGENCY_PREPAREDNESS_DEFICIENCIES, 
REPORT_DATE, 
COUNT_OF_QUALITY_OF_LIFE_AND_CARE_DEFICIENCIES, 
COUNT_OF_ILLUMINATION_AND_EMERGENCY_POWER_DEFICIENCIES, 
COUNT_OF_CONSTRUCTION_DEFICIENCIES, CMS_CERTIFICATION_NUMBER_CCN, 
COUNT_OF_FIRE_ALARM_SYSTEMS_DEFICIENCIES, 
COUNT_OF_HAZARDOUS_AREA_DEFICIENCIES, 
COUNT_OF_INTERIOR_DEFICIENCIES, 
LOCATION, 
COUNT_OF_MISCELLANEOUS_DEFICIENCIES, 
COUNT_OF_ENVIRONMENTAL_DEFICIENCIES, 
TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES, 
INSPECTION_CYCLE, 
COUNT_OF_AUTOMATIC_SPRINKLER_SYSTEMS_DEFICIENCIES
FROM {{ source('BRONZE', 'NH_SURVEY_SUMMARY') }}