{{
  config(
    materialized="table",
    schema=set_schema_based_on_folder()
  )
}}
SELECT 
    BASELINE_PERIOD_FY_2019_NATIONAL_AVERAGE_READMISSION_RATE, 
    RANGE_OF_INCENTIVE_PAYMENT_MULTIPLIERS, 
    FY_2024_ACHIEVEMENT_THRESHOLD, 
    TOTAL_AMOUNT_OF_VALUE_BASED_INCENTIVE_PAYMENTS, 
    RANGE_OF_VALUE_BASED_INCENTIVE_PAYMENTS, 
    REPORT_MONTH, FY_2024_BENCHMARK, 
    REPORT_DATE, 
    RANGE_OF_PERFORMANCE_SCORES, 
    PERFORMANCE_PERIOD_FY_2022_NATIONAL_AVERAGE_READMISSION_RATE, 
    TOTAL_NUMBER_OF_SNFS_RECEIVING_VALUE_BASED_INCENTIVE_PAYMENTS
FROM {{ source('BRONZE', 'SNF_VBP_AGGREGATE_PERFORMANCE') }}
