SELECT 
    CMS_CERTIFICATION_NUMBER_CCN,
MEASURE_DATE_RANGE,
FOOTNOTE,
REPORT_MONTH,
START_DATE,
SCORE,
MEASURE_CODE,
END_DATE,
REPORT_DATE
FROM {{ source('BRONZE', 'SNF_QRP_NATIONAL_DATA') }}
